spring.application.name=LeafDocBackend

spring.config.import=optional:file:.env[.properties]

server.port=8080 #${PORT:8080} #8080 default val
server.address=0.0.0.0
server.servlet.context-path=/api

# Logs
#logging.level.root = DEBUG #INFO
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernet.SQL=DEBUG  # shows sql query
#logging.level.org.hibernet.orm.jdbc.bind=TRACE #shows sql param values

# Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/db_name_placeholder
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto= update #validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true

# JWT
app.jwt.secret=<secret key hash>
app.jwt.expiration=86400000 #one day (in ms)

# CORS
app.cors.allowed-origin=http://localhost:5173

# ML Service
app.ml.service.host=0.0.0.0
app.ml.service.port=8000
app.ml.service.key=SECRET_KEY

# Mail
app.mail.from=${MAIL_FROM}

# OTP
app.otp.expiration=300

#spring.profiles.active=local # activate local properties